baseURL = "www.example.com"
languageCode = "en-us"
title = "Winston."
themesDir = "../.."
theme = "winston-hugo"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"