baseURL = "www.example.com"
languageCode = "en-us"
title = "Winston Hugo"
themesDir = "../.."
theme = "winston-hugo"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
paginate = 2

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"